// 地区选项
export const regionOptions = [
  {
    value: 'China',
    label: 'China'
  },
  {
    value: 'U.S.',
    label: 'U.S.'
  },
  {
    value: 'Europe',
    label: 'Europe',
    children: [
      { value: 'Austria', label: 'Austria' },
      { value: 'Belgium', label: 'Belgium' },
      { value: 'Bulgaria', label: 'Bulgaria' },
      { value: 'Switzerland', label: 'Switzerland' },
      { value: 'Czech Republic', label: 'Czech Republic' },
      { value: 'Germany', label: 'Germany' },
      { value: 'Denmark', label: 'Denmark' },
      { value: 'Estonia', label: 'Estonia' },
      { value: 'Greece', label: 'Greece' },
      { value: 'Spain', label: 'Spain' },
      { value: 'Finland', label: 'Finland' },
      { value: 'France', label: 'France' },
      { value: 'Croatia', label: 'Croatia' },
      { value: 'Hungary', label: 'Hungary' },
      { value: 'Ireland', label: 'Ireland' },
      { value: 'Italy', label: 'Italy' },
      { value: 'Lithuania', label: 'Lithuania' },
      { value: 'Luxembourg', label: 'Luxembourg' },
      { value: 'Latvia', label: 'Latvia' },
      { value: 'Moldova', label: 'Moldova' },
      { value: 'Malta', label: 'Malta' },
      { value: 'Netherlands', label: 'Netherlands' },
      { value: 'Norway', label: 'Norway' },
      { value: 'Poland', label: 'Poland' },
      { value: 'Portugal', label: 'Portugal' },
      { value: 'Romania', label: 'Romania' },
      { value: 'Sweden', label: 'Sweden' },
      { value: 'Slovenia', label: 'Slovenia' },
      { value: 'Slovakia', label: 'Slovakia' },
      { value: 'Ukraine', label: 'Ukraine' },
      { value: 'Liechtenstein', label: 'Liechtenstein' },
      { value: 'United Kingdom', label: 'United Kingdom' },
      { value: 'Iceland', label: 'Iceland' },
      { value: 'Cyprus', label: 'Cyprus' },
    ]
  },
  {
    value: 'other',
    label: 'Other',
    children: [
      // { value: 'HongKong, China', label: 'Hong Kong' },
      { value: 'Japan', label: 'Japan' },
      { value: 'korea', label: 'Korea' },
      // { value: 'TaiWan, China', label: 'Taiwan' },
      { value: 'Australia', label: 'Australia' },
      { value: 'Newzealand', label: 'New Zealand' },
      { value: 'Thailand', label: 'Thailand' },
      { value: 'Singapore', label: 'Singapore' },
      { value: 'Malaysia', label: 'Malaysia' },
      { value: 'Colombia', label: 'Colombia' },
      { value: 'Peru', label: 'Peru' },
      { value: 'Brazil', label: 'Brazil' }
    ]
  }
]


export const regionOptions2 = [
  {
    value: 'China',
    label: 'China'
  },
  {
    value: 'U.S.',
    label: 'U.S.'
  },
  {
    value: 'Europe',
    label: 'Europe',
  }
]

// 可用年份
export const availableYears = ['2022', '2024*', '2025*']

export const availableYearsForAAM = ['Social Media Text Data 2015-2024*', 'Bibliometric Text Data 2015-2024*']

export const availableYearsForEVCReviewData = ['2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024']

// China E-bus Data 类型选项
export const chinaEBusTypes = [
  { value: 'BusRouteStopData', label: 'Bus Route and Stop Data (2025)' },
  { value: 'BusOperationData', label: 'Bus Operation Data (2025)' },
  { value: 'RoadNetworkData', label: 'Road Network Data (2025)' }
]

// China E-bus Data 城市选项
export const chinaEBusCities = [
  { value: 'all', label: 'All Cities' },
  { value: 'Beijing', label: 'Beijing' },
  { value: 'Tianjin', label: 'Tianjin' },
  { value: 'Shijiazhuang', label: 'Shijiazhuang' },
  { value: 'Qinhuangdao', label: 'Qinhuangdao' },
  { value: 'Handan', label: 'Handan' },
  { value: 'Xingtai', label: 'Xingtai' },
  { value: 'Baoding', label: 'Baoding' },
  { value: 'Zhangjiakou', label: 'Zhangjiakou' },
  { value: 'Chengde', label: 'Chengde' },
  { value: 'Cangzhou', label: 'Cangzhou' },
  { value: 'Langfang', label: 'Langfang' },
  { value: 'Hengshui', label: 'Hengshui' },
  { value: 'Taiyuan', label: 'Taiyuan' },
  { value: 'Datong', label: 'Datong' },
  { value: 'Changzhi', label: 'Changzhi' },
  { value: 'Jincheng', label: 'Jincheng' },
  { value: 'Shuozhou', label: 'Shuozhou' },
  { value: 'Yuncheng', label: 'Yuncheng' },
  { value: 'Xinzhou', label: 'Xinzhou' },
  { value: 'Linfen', label: 'Linfen' },
  { value: 'Lvliang', label: 'Lvliang' },
  { value: 'Hohhot', label: 'Hohhot' },
  { value: 'Baotou', label: 'Baotou' },
  { value: 'Chifeng', label: 'Chifeng' },
  { value: 'Ordos', label: 'Ordos' },
  { value: 'Ulanqab', label: 'Ulanqab' },
  { value: 'Shenyang', label: 'Shenyang' },
  { value: 'Anshan', label: 'Anshan' },
  { value: 'Fushun', label: 'Fushun' },
  { value: 'Dandong', label: 'Dandong' },
  { value: 'Jinzhou', label: 'Jinzhou' },
  { value: 'Yingkou', label: 'Yingkou' },
  { value: 'Liaoyang', label: 'Liaoyang' },
  { value: 'Panjin', label: 'Panjin' },
  { value: 'Tieling', label: 'Tieling' },
  { value: 'Chaoyang', label: 'Chaoyang' },
  { value: 'Changchun', label: 'Changchun' },
  { value: 'Jilin', label: 'Jilin' },
  { value: 'Siping', label: 'Siping' },
  { value: 'Tonghua', label: 'Tonghua' },
  { value: 'Songyuan', label: 'Songyuan' },
  { value: 'Harbin', label: 'Harbin' },
  { value: 'Qiqihar', label: 'Qiqihar' },
  { value: 'Shuangyashan', label: 'Shuangyashan' },
  { value: 'Daqing', label: 'Daqing' },
  { value: 'Jiamusi', label: 'Jiamusi' },
  { value: 'Qitaihe', label: 'Qitaihe' },
  { value: 'Mudanjiang', label: 'Mudanjiang' },
  { value: 'Heihe', label: 'Heihe' },
  { value: 'Suihua', label: 'Suihua' },
  { value: 'Shanghai', label: 'Shanghai' },
  { value: 'Nanjing', label: 'Nanjing' },
  { value: 'Xuzhou', label: 'Xuzhou' },
  { value: 'Changzhou', label: 'Changzhou' },
  { value: 'Suzhou, Jiangsu', label: 'Suzhou, Jiangsu' },
  { value: 'Nantong', label: 'Nantong' },
  { value: 'Lianyungang', label: 'Lianyungang' },
  { value: 'Huai\'an', label: 'Huai\'an' },
  { value: 'Yancheng', label: 'Yancheng' },
  { value: 'Yangzhou', label: 'Yangzhou' },
  { value: 'Zhenjiang', label: 'Zhenjiang' },
  { value: 'Taizhou, Jiangsu', label: 'Taizhou, Jiangsu' },
  { value: 'Suqian', label: 'Suqian' },
  { value: 'Hangzhou', label: 'Hangzhou' },
  { value: 'Ningbo', label: 'Ningbo' },
  { value: 'Wenzhou', label: 'Wenzhou' },
  { value: 'Jiaxing', label: 'Jiaxing' },
  { value: 'Huzhou', label: 'Huzhou' },
  { value: 'Shaoxing', label: 'Shaoxing' },
  { value: 'Jinhua', label: 'Jinhua' },
  { value: 'Quzhou', label: 'Quzhou' },
  { value: 'Zhoushan', label: 'Zhoushan' },
  { value: 'Taizhou, Zhejiang', label: 'Taizhou, Zhejiang' },
  { value: 'Wuhu', label: 'Wuhu' },
  { value: 'Bengbu', label: 'Bengbu' },
  { value: 'Huainan', label: 'Huainan' },
  { value: 'Ma\'anshan', label: 'Ma\'anshan' },
  { value: 'Huaibei', label: 'Huaibei' },
  { value: 'Tongling', label: 'Tongling' },
  { value: 'Anqing', label: 'Anqing' },
  { value: 'Chuzhou', label: 'Chuzhou' },
  { value: 'Fuyang', label: 'Fuyang' },
  { value: 'Suzhou, Anhui', label: 'Suzhou, Anhui' },
  { value: 'Lu\'an', label: 'Lu\'an' },
  { value: 'Fuzhou, Fujian', label: 'Fuzhou, Fujian' },
  { value: 'Xiamen', label: 'Xiamen' },
  { value: 'Putian', label: 'Putian' },
  { value: 'Sanming', label: 'Sanming' },
  { value: 'Quanzhou', label: 'Quanzhou' },
  { value: 'Zhangzhou', label: 'Zhangzhou' },
  { value: 'Nanping', label: 'Nanping' },
  { value: 'Longyan', label: 'Longyan' },
  { value: 'Ningde', label: 'Ningde' },
  { value: 'Nanchang', label: 'Nanchang' },
  { value: 'Jingdezhen', label: 'Jingdezhen' },
  { value: 'Pingxiang', label: 'Pingxiang' },
  { value: 'Jiujiang', label: 'Jiujiang' },
  { value: 'Xinyu', label: 'Xinyu' },
  { value: 'Yingtan', label: 'Yingtan' },
  { value: 'Ganzhou', label: 'Ganzhou' },
  { value: 'Ji\'an', label: 'Ji\'an' },
  { value: 'Yichun', label: 'Yichun' },
  { value: 'Fuzhou, Jiangxi', label: 'Fuzhou, Jiangxi' },
  { value: 'Shangrao', label: 'Shangrao' },
  { value: 'Jinan', label: 'Jinan' },
  { value: 'Qingdao', label: 'Qingdao' },
  { value: 'Zibo', label: 'Zibo' },
  { value: 'Zaozhuang', label: 'Zaozhuang' },
  { value: 'Dongying', label: 'Dongying' },
  { value: 'Yantai', label: 'Yantai' },
  { value: 'Weifang', label: 'Weifang' },
  { value: 'Jining', label: 'Jining' },
  { value: 'Tai\'an', label: 'Tai\'an' },
  { value: 'Weihai', label: 'Weihai' },
  { value: 'Rizhao', label: 'Rizhao' },
  { value: 'Dezhou', label: 'Dezhou' },
  { value: 'Liaocheng', label: 'Liaocheng' },
  { value: 'Binzhou', label: 'Binzhou' },
  { value: 'Heze', label: 'Heze' },
  { value: 'Kaifeng', label: 'Kaifeng' },
  { value: 'Luoyang', label: 'Luoyang' },
  { value: 'Pingdingshan', label: 'Pingdingshan' },
  { value: 'Anyang', label: 'Anyang' },
  { value: 'Hebi', label: 'Hebi' },
  { value: 'Xinxiang', label: 'Xinxiang' },
  { value: 'Jiaozuo', label: 'Jiaozuo' },
  { value: 'Puyang', label: 'Puyang' },
  { value: 'Luohe', label: 'Luohe' },
  { value: 'Sanmenxia', label: 'Sanmenxia' },
  { value: 'Nanyang', label: 'Nanyang' },
  { value: 'Shangqiu', label: 'Shangqiu' },
  { value: 'Xinyang', label: 'Xinyang' },
  { value: 'Zhoukou', label: 'Zhoukou' },
  { value: 'Zhumadian', label: 'Zhumadian' },
  { value: 'Wuhan', label: 'Wuhan' },
  { value: 'Huangshi', label: 'Huangshi' },
  { value: 'Shiyan', label: 'Shiyan' },
  { value: 'Yichang', label: 'Yichang' },
  { value: 'Xiangyang', label: 'Xiangyang' },
  { value: 'Jingmen', label: 'Jingmen' },
  { value: 'Jingzhou', label: 'Jingzhou' },
  { value: 'Xianning', label: 'Xianning' },
  { value: 'Suizhou', label: 'Suizhou' },
  { value: 'Changsha', label: 'Changsha' },
  { value: 'Xiangtan', label: 'Xiangtan' },
  { value: 'Hengyang', label: 'Hengyang' },
  { value: 'Shaoyang', label: 'Shaoyang' },
  { value: 'Yueyang', label: 'Yueyang' },
  { value: 'Changde', label: 'Changde' },
  { value: 'Yiyang', label: 'Yiyang' },
  { value: 'Chenzhou', label: 'Chenzhou' },
  { value: 'Yongzhou', label: 'Yongzhou' },
  { value: 'Huaihua', label: 'Huaihua' },
  { value: 'Loudi', label: 'Loudi' },
  { value: 'Guangzhou', label: 'Guangzhou' },
  { value: 'Shenzhen', label: 'Shenzhen' },
  { value: 'Zhuhai', label: 'Zhuhai' },
  { value: 'Shantou', label: 'Shantou' },
  { value: 'Foshan', label: 'Foshan' },
  { value: 'Jiangmen', label: 'Jiangmen' },
  { value: 'Zhanjiang', label: 'Zhanjiang' },
  { value: 'Maoming', label: 'Maoming' },
  { value: 'Zhaoqing', label: 'Zhaoqing' },
  { value: 'Huizhou', label: 'Huizhou' },
  { value: 'Meizhou', label: 'Meizhou' },
  { value: 'Shanwei', label: 'Shanwei' },
  { value: 'Heyuan', label: 'Heyuan' },
  { value: 'Yangjiang', label: 'Yangjiang' },
  { value: 'Qingyuan', label: 'Qingyuan' },
  { value: 'Dongguan', label: 'Dongguan' },
  { value: 'Zhongshan', label: 'Zhongshan' },
  { value: 'Chaozhou', label: 'Chaozhou' },
  { value: 'Jieyang', label: 'Jieyang' },
  { value: 'Yunfu', label: 'Yunfu' },
  { value: 'Nanning', label: 'Nanning' },
  { value: 'Liuzhou', label: 'Liuzhou' },
  { value: 'Guilin', label: 'Guilin' },
  { value: 'Wuzhou', label: 'Wuzhou' },
  { value: 'Beihai', label: 'Beihai' },
  { value: 'Guigang', label: 'Guigang' },
  { value: 'Yulin', label: 'Yulin' },
  { value: 'Baise', label: 'Baise' },
  { value: 'Hechi', label: 'Hechi' },
  { value: 'Laibin', label: 'Laibin' },
  { value: 'Haikou', label: 'Haikou' },
  { value: 'Sanya', label: 'Sanya' },
  { value: 'Chongqing', label: 'Chongqing' },
  { value: 'Chengdu', label: 'Chengdu' },
  { value: 'Zigong', label: 'Zigong' },
  { value: 'Panzhihua', label: 'Panzhihua' },
  { value: 'Luzhou', label: 'Luzhou' },
  { value: 'Mianyang', label: 'Mianyang' },
  { value: 'Neijiang', label: 'Neijiang' },
  { value: 'Nanchong', label: 'Nanchong' },
  { value: 'Meishan', label: 'Meishan' },
  { value: 'Yibin', label: 'Yibin' },
  { value: 'Dazhou', label: 'Dazhou' },
  { value: 'Ya\'an', label: 'Ya\'an' },
  { value: 'Ziyang', label: 'Ziyang' },
  { value: 'Guiyang', label: 'Guiyang' },
  { value: 'Liupanshui', label: 'Liupanshui' },
  { value: 'Zunyi', label: 'Zunyi' },
  { value: 'Anshun', label: 'Anshun' },
  { value: 'Bijie', label: 'Bijie' },
  { value: 'Tongren', label: 'Tongren' },
  { value: 'Kunming', label: 'Kunming' },
  { value: 'Qujing', label: 'Qujing' },
  { value: 'Yuxi', label: 'Yuxi' },
  { value: 'Zhaotong', label: 'Zhaotong' },
  { value: 'Lhasa', label: 'Lhasa' },
  { value: 'Xi\'an', label: 'Xi\'an' },
  { value: 'Tongchuan', label: 'Tongchuan' },
  { value: 'Baoji', label: 'Baoji' },
  { value: 'Xianyang', label: 'Xianyang' },
  { value: 'Lanzhou', label: 'Lanzhou' },
  { value: 'Tianshui', label: 'Tianshui' },
  { value: 'Zhangye', label: 'Zhangye' },
  { value: 'Jiuquan', label: 'Jiuquan' },
  { value: 'Qingyang', label: 'Qingyang' },
  { value: 'Xining', label: 'Xining' },
  { value: 'Yinchuan', label: 'Yinchuan' },
  { value: 'Guyuan', label: 'Guyuan' },
  { value: 'Urumqi', label: 'Urumqi' },
  { value: 'Hami', label: 'Hami' }
]
